AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:

  QrarApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-qrar-api
      StageName: Prod
      Auth:
        ApiKeyRequired: false

  ShortenUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-qrar-shorten-url-func
      CodeUri: ../backend/shorten-url
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloGfmiApi:
          Type: Api
          Properties:
            Path: /api/shorten-url
            Method: POST
            RestApiId: !Ref QrarApi

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
        AccessControl: Private
        BucketName: !Sub ${AWS::StackName}-qrar-frontend-bucket
        Tags:
            - Key: description
              Value: "Stores Web files for QRAR Frontend"

  PlayBucket:
    Type: AWS::S3::Bucket
    Properties:
        AccessControl: Private
        BucketName: !Sub ${AWS::StackName}-qrar-play-bucket
        Tags:
            - Key: description
              Value: "Stores Web files for QRAR Play"

  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Origin Access Identity for QRAR Frontend'

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FrontendBucket
                - /*

  PlayBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PlayBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref PlayBucket
                - /*

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3-frontend-bucket
            DomainName: !Sub '${FrontendBucket}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
          - Id: S3-play-bucket
            DomainName: !Sub '${PlayBucket}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
          - Id: Api-shorten-url
            DomainName: !Sub '${QrarApi}.execute-api.${AWS::Region}.amazonaws.com'
            OriginPath: '/Prod'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        Enabled: true
        Comment: CloudFront Distribution for Qrar Frontend
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3-frontend-bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: 'index.html'
        CustomErrorResponses:
        - ErrorCode: 403
          ResponsePagePath: "/index.html"
          ResponseCode: 200
        CacheBehaviors:
          - PathPattern: '/api*/*'
            TargetOriginId: Api-shorten-url
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            ForwardedValues:
              QueryString: true
          - PathPattern: '/play*/*'
            TargetOriginId: Api-shorten-url
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            ForwardedValues:
              QueryString: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:

  FrontendUrl:
    Description: 'Frontend URL'
    Value: !GetAtt FrontendDistribution.DomainName

  ShortenUrlApiUrl:
    Description: 'URL'
    Value: !Sub 'https://${QrarApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorten-url'